### ISSUE TITLE
get_score_one_image函数定义是空的，怎么基于训练好的模型推理单张图片

### ISSUE THREAD

**Issue by xxaier** [woshidandan/Image-Aesthetics-Assessment#1]
您好，我在做一个基于clip搜索生成图片的搜索引擎，发现有很多图片相关性很高但是质量不高，为了数据冷启动，想加一个质量因子。

我想用 Image-Aesthetics-Assessment ， 但是发现 get_score_one_image函数定义是空的，怎么基于训练好的模型推理单张图片，能给一个完整的演示代码吗？（我对写网站比较熟悉，转过一些模型到ONNX，但是对AI开发不太熟悉）

**Comment by xxaier** [comment]
我自己搞定了

https://github.com/xxai-fork/Image-Aesthetics-Assessment/blob/main/AVA/test.py
```
#!/usr/bin/env python

import os
import torch
from os.path import join
from PIL import Image
from models.dat import DAT
import yaml
from torchvision import transforms
import numpy as np
from fire import Fire


def get_score(y_pred):
  w = torch.from_numpy(np.linspace(1, 10, 10))
  w = w.type(torch.FloatTensor)
  w = w.to(device)

  w_batch = w.repeat(y_pred.size(0), 1)

  score = (y_pred * w_batch).sum(dim=1)
  score_np = score.data.cpu().numpy()
  return score_np[0]


IMAGE_NET_MEAN = [0.485, 0.456, 0.406]
IMAGE_NET_STD = [0.229, 0.224, 0.225]
normalize = transforms.Normalize(mean=IMAGE_NET_MEAN, std=IMAGE_NET_STD)
transform = transforms.Compose([transforms.ToTensor(), normalize])

device = torch.device("cpu")


def load_model(model_name):
  ck = torch.load(model_name, map_location=torch.device('mps'))

  with open('./configs/dat_base.yaml') as f:
    conf = yaml.load(f, Loader=yaml.FullLoader)['MODEL']['DAT']

  model = DAT(**conf)
  model.load_state_dict(ck)
  model.eval()
  model.to(device)
  return model


def jpg_iter(root):
  for root, dirs, files in os.walk(join('../jpg', root)):
    # 遍历当前目录下所有文件
    for filename in files:
      # 检查文件名是否以'.jpg'结尾
      if filename.endswith('.jpg'):
        # 拼接完整路径
        jpg_path = os.path.join(root, filename)
        yield jpg_path


def score_dir(root, model):
  n = 0
  for i in jpg_iter(root):
    img = Image.open(i).resize((224, 224))
    img = transform(img)
    # 参数是一个图片的数组， unsqueeze相当于创建一个只有一个图片的数组
    img = img.unsqueeze(0)
    img = img.to(device)

    with torch.no_grad():
      pred, _, _ = model(img)

    pred = get_score(pred)
    print(i, pred)
    n += pred
  return n


@Fire
def main(model_name):
  model = load_model(model_name)
  print(model_name + '\n' +
        str(score_dir('good', model) - score_dir('bad', model)))
```

**Comment by huangyangke** [comment]
> 我自己搞定了
> 
> https://github.com/xxai-fork/Image-Aesthetics-Assessment/blob/main/AVA/test.py
> 
> ```
> #!/usr/bin/env python
> 
> import os
> import torch
> from os.path import join
> from PIL import Image
> from models.dat import DAT
> import yaml
> from torchvision import transforms
> import numpy as np
> from fire import Fire
> 
> 
> def get_score(y_pred):
>   w = torch.from_numpy(np.linspace(1, 10, 10))
>   w = w.type(torch.FloatTensor)
>   w = w.to(device)
> 
>   w_batch = w.repeat(y_pred.size(0), 1)
> 
>   score = (y_pred * w_batch).sum(dim=1)
>   score_np = score.data.cpu().numpy()
>   return score_np[0]
> 
> 
> IMAGE_NET_MEAN = [0.485, 0.456, 0.406]
> IMAGE_NET_STD = [0.229, 0.224, 0.225]
> normalize = transforms.Normalize(mean=IMAGE_NET_MEAN, std=IMAGE_NET_STD)
> transform = transforms.Compose([transforms.ToTensor(), normalize])
> 
> device = torch.device("cpu")
> 
> 
> def load_model(model_name):
>   ck = torch.load(model_name, map_location=torch.device('mps'))
> 
>   with open('./configs/dat_base.yaml') as f:
>     conf = yaml.load(f, Loader=yaml.FullLoader)['MODEL']['DAT']
> 
>   model = DAT(**conf)
>   model.load_state_dict(ck)
>   model.eval()
>   model.to(device)
>   return model
> 
> 
> def jpg_iter(root):
>   for root, dirs, files in os.walk(join('../jpg', root)):
>     # 遍历当前目录下所有文件
>     for filename in files:
>       # 检查文件名是否以'.jpg'结尾
>       if filename.endswith('.jpg'):
>         # 拼接完整路径
>         jpg_path = os.path.join(root, filename)
>         yield jpg_path
> 
> 
> def score_dir(root, model):
>   n = 0
>   for i in jpg_iter(root):
>     img = Image.open(i).resize((224, 224))
>     img = transform(img)
>     # 参数是一个图片的数组， unsqueeze相当于创建一个只有一个图片的数组
>     img = img.unsqueeze(0)å
>     img = img.to(device)
> 
>     with torch.no_grad():
>       pred, _, _ = model(img)
> 
>     pred = get_score(pred)
>     print(i, pred)
>     n += pred
>   return n
> 
> 
> @Fire
> def main(model_name):
>   model = load_model(model_name)
>   print(model_name + '\n' +
>         str(score_dir('good', model) - score_dir('bad', model)))
> ```



> 我自己搞定了
> 
> https://github.com/xxai-fork/Image-Aesthetics-Assessment/blob/main/AVA/test.py
> 
> ```
> #!/usr/bin/env python
> 
> import os
> import torch
> from os.path import join
> from PIL import Image
> from models.dat import DAT
> import yaml
> from torchvision import transforms
> import numpy as np
> from fire import Fire
> 
> 
> def get_score(y_pred):
>   w = torch.from_numpy(np.linspace(1, 10, 10))
>   w = w.type(torch.FloatTensor)
>   w = w.to(device)
> 
>   w_batch = w.repeat(y_pred.size(0), 1)
> 
>   score = (y_pred * w_batch).sum(dim=1)
>   score_np = score.data.cpu().numpy()
>   return score_np[0]
> 
> 
> IMAGE_NET_MEAN = [0.485, 0.456, 0.406]
> IMAGE_NET_STD = [0.229, 0.224, 0.225]
> normalize = transforms.Normalize(mean=IMAGE_NET_MEAN, std=IMAGE_NET_STD)
> transform = transforms.Compose([transforms.ToTensor(), normalize])
> 
> device = torch.device("cpu")
> 
> 
> def load_model(model_name):
>   ck = torch.load(model_name, map_location=torch.device('mps'))
> 
>   with open('./configs/dat_base.yaml') as f:
>     conf = yaml.load(f, Loader=yaml.FullLoader)['MODEL']['DAT']
> 
>   model = DAT(**conf)
>   model.load_state_dict(ck)
>   model.eval()
>   model.to(device)
>   return model
> 
> 
> def jpg_iter(root):
>   for root, dirs, files in os.walk(join('../jpg', root)):
>     # 遍历当前目录下所有文件
>     for filename in files:
>       # 检查文件名是否以'.jpg'结尾
>       if filename.endswith('.jpg'):
>         # 拼接完整路径
>         jpg_path = os.path.join(root, filename)
>         yield jpg_path
> 
> 
> def score_dir(root, model):
>   n = 0
>   for i in jpg_iter(root):
>     img = Image.open(i).resize((224, 224))
>     img = transform(img)
>     # 参数是一个图片的数组， unsqueeze相当于创建一个只有一个图片的数组
>     img = img.unsqueeze(0)
>     img = img.to(device)
> 
>     with torch.no_grad():
>       pred, _, _ = model(img)
> 
>     pred = get_score(pred)
>     print(i, pred)
>     n += pred
>   return n
> 
> 
> @Fire
> def main(model_name):
>   model = load_model(model_name)
>   print(model_name + '\n' +
>         str(score_dir('good', model) - score_dir('bad', model)))
> ```

导出onnx之后，发现输出不一致，测试后精度会下降2个点左右

**Comment by sneccc** [comment]
@huangyangke @xxaier do you know if its possible to finetune this or train from scratch on a manual dataset like https://github.com/deforum-art/aestylo/blob/main/train_predictor.py ?
